version: '3.4'

services:
    webmvc:
        image: webmvc
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
        ports:
            - 5000:80